apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: front-deploy-pr-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: front-deploy-pipeline
  params:
  - name: source-url
    value: "git@github.com:cloud-native-garage-method-japan-cohort/orion-frontend.git"
  - name: source-branch
    value: "main"
  - name: manifest-url
    value: "git@github.com:cloud-native-garage-method-japan-cohort/orion-manifest.git"
  - name: manifest-branch
    value: "feature/add-front-manifest"
#  - name: commit-message
#    value: "$(tt.params.commit-message)"
  - name: image-repo
    value: "quay.io/tyonesaka/front-app"
  - name: app-name
    value: "front-app"
  - name: app-namespace
    value: "team-orion"
  - name: manifest-dir
    value: "front"
  workspaces:
  - name: pipeline-shared-data
    persistentvolumeclaim:
      claimName: team-orion-pvc
