apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: back-deploy-pr-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: back-deploy-pipeline
  params:
  - name: source-url
    value: "git@github.com:cloud-native-garage-method-japan-cohort/orion-backend.git"
  - name: source-branch
    value: "master"
  - name: manifest-url
    value: "git@github.com:cloud-native-garage-method-japan-cohort/orion-manifest.git"
  - name: manifest-branch
    value: "feature/add-back-manifest"
#  - name: commit-message
#    value: "$(tt.params.commit-message)"
  - name: image-repo
    value: "quay.io/tyonesaka/back-api"
  - name: app-name
    value: "back-api"
  - name: app-namespace
    value: "team-orion"
  - name: manifest-dir
    value: "back"
  - name: source-dir
    value: ""
  workspaces:
  - name: pipeline-shared-data
    persistentvolumeclaim:
      claimName: team-orion-pvc
