apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
  labels:
    app: front-app
    version: "1.0"
spec:
  selector:
    matchLabels:
      app: front-app
  replicas: 1
  template:
    metadata:
      labels:
        app: front-app
        version: "1.0"
    spec:
      containers:
      - name: front-app
        image: front-app # Overwrite it with the kustomize command.
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registory-bot
