apiVersion: v1
kind: Service
metadata:
  name: front-app
  labels:
    app: front-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: front-app
  type: ClusterIP
